### ISSUE TITLE
Code Diff

### ISSUE THREAD

**Issue by gitPratikSingh** [PacktPublishing/Mastering-Spark-for-Data-Science#3]
Hi, I have been following the book to implement the recommender app. I found the code in the repo is

```
val hashRDD = sampleRDD.map({case (songId, sample) =>
      ((sample.hash, songId), Array(sample.id))
    }).reduceByKey(_ ++ _).mapValues(a => a.mkString(",")).map({case ((hash, songId), sampleIds) =>
      (hash, songId)
    }).groupByKey().mapValues(it => it.toList).map({case (id, songs) =>
      Hash(id, songs)
    })

```
while the book has this snippet. I think the book's code is accurate. The above query does the same thing but in a convoluted way(I do not understand  the use of 'sampleIds' is the query. It is not saved nor used anywhere)
```

val hashRDD = sampleRdd.map({case(songId, sample) => 
        (sample.hash(), songId)
    }).groupByKey().map({case(hash, songs) => Hash(hash, songs.toList)})
    
```

If possible please let me know if there is any functional difference between the two queries.

**Comment by mrhalle** [comment]
Yes you are correct! The repo code is a first attempt that somehow made its way into GIT, whereas the book code is the polished version. Still, a good example of optimization!
